# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dining with the EW's
email: ews@williams.ee
description: > # this means to ignore newlines until "baseurl:"
  Welcome to Dining with the EW's! We're enthusiasitic about hospitality, and want to encourage more people to get involved. Every month we'll teach you how to throw a great dinner party. New videos every Wednesday.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://williams.ee" # the base hostname & protocol for your site


paginate: 5
paginate_path: /:num/

# SEO plugin settings
logo: /resources/images/logo.png

twitter_username: EWDining
twitter:
  username: EWDining
facebook:
  publisher: EWDining

github_username:  malacandrian

# Build settings
encoding: utf-8
markdown: kramdown
include:
  - _pages
  - _posts
exclude:
  - .gitignore
  - .gitmodules
  - CNAME
  - LICENSE.md
  - README.md
gems:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
